replicaCount: 1

image:
  repository: apexshieldacrdev.azurecr.io/life-insurance-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "life-insurance-app-helm"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: true   # Change this from false to true
  minReplicas: 1  # Minimum pods running when traffic is low
  maxReplicas: 3  # Maximum pods allowed to scale up under heavy load
  targetCPUUtilizationPercentage: 50  # Scales up if average CPU usage exceeds 50%

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}